#!/bin/bash

# Deletes Elasticsearch indices.
#
# Delete the index containing the Specimen document type:
# ./delete Specimen
#
# Delete the indices containing the Specimen document type:
# and the GeoArea document type:
# ./delete Specimen
#
# Delete all indices managed by the NBA:
# ./delete --all
#
# Delete whichever indices you like
# ./delete --raw .kibana taxon


. ./include.sh

java -cp ${classpath} $JAVA_OPTS ${root_package}.NbaDeleteIndex $@

