//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.09.01 at 04:00:28 PM CEST 
//


package nl.naturalis.nba.dao.es.format.config;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ConditionsConfig complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ConditionsConfig">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="condition" type="{http://data.naturalis.nl/nba-dataset-config}ConditionConfig" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *       &lt;attribute name="operator" type="{http://data.naturalis.nl/nba-dataset-config}LogicalOperatorConfig" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ConditionsConfig", propOrder = {
    "condition"
})
public class ConditionsConfig {

    @XmlElement(required = true)
    protected List<ConditionConfig> condition;
    @XmlAttribute(name = "operator")
    protected LogicalOperatorConfig operator;

    /**
     * Gets the value of the condition property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the condition property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCondition().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ConditionConfig }
     * 
     * 
     */
    public List<ConditionConfig> getCondition() {
        if (condition == null) {
            condition = new ArrayList<ConditionConfig>();
        }
        return this.condition;
    }

    /**
     * Gets the value of the operator property.
     * 
     * @return
     *     possible object is
     *     {@link LogicalOperatorConfig }
     *     
     */
    public LogicalOperatorConfig getOperator() {
        return operator;
    }

    /**
     * Sets the value of the operator property.
     * 
     * @param value
     *     allowed object is
     *     {@link LogicalOperatorConfig }
     *     
     */
    public void setOperator(LogicalOperatorConfig value) {
        this.operator = value;
    }

}
