//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.09.01 at 04:00:28 PM CEST 
//


package nl.naturalis.nba.dao.es.format.config;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for EntityConfig complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="EntityConfig">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="document" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="entity-object" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="query-spec" type="{http://data.naturalis.nl/nba-dataset-config}QuerySpecConfig" minOccurs="0"/>
 *         &lt;element name="field" type="{http://data.naturalis.nl/nba-dataset-config}FieldConfig" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *       &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "EntityConfig", propOrder = {
    "document",
    "entityObject",
    "querySpec",
    "field"
})
public class EntityConfig {

    protected String document;
    @XmlElement(name = "entity-object")
    protected String entityObject;
    @XmlElement(name = "query-spec")
    protected QuerySpecConfig querySpec;
    @XmlElement(required = true)
    protected List<FieldConfig> field;
    @XmlAttribute(name = "name")
    protected String name;

    /**
     * Gets the value of the document property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDocument() {
        return document;
    }

    /**
     * Sets the value of the document property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDocument(String value) {
        this.document = value;
    }

    /**
     * Gets the value of the entityObject property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEntityObject() {
        return entityObject;
    }

    /**
     * Sets the value of the entityObject property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEntityObject(String value) {
        this.entityObject = value;
    }

    /**
     * Gets the value of the querySpec property.
     * 
     * @return
     *     possible object is
     *     {@link QuerySpecConfig }
     *     
     */
    public QuerySpecConfig getQuerySpec() {
        return querySpec;
    }

    /**
     * Sets the value of the querySpec property.
     * 
     * @param value
     *     allowed object is
     *     {@link QuerySpecConfig }
     *     
     */
    public void setQuerySpec(QuerySpecConfig value) {
        this.querySpec = value;
    }

    /**
     * Gets the value of the field property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the field property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getField().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link FieldConfig }
     * 
     * 
     */
    public List<FieldConfig> getField() {
        if (field == null) {
            field = new ArrayList<FieldConfig>();
        }
        return this.field;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

}
