//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.09.01 at 04:00:28 PM CEST 
//


package nl.naturalis.nba.dao.es.format.config;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the nl.naturalis.nba.dao.es.format.config package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: nl.naturalis.nba.dao.es.format.config
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ConditionConfig }
     * 
     */
    public ConditionConfig createConditionConfig() {
        return new ConditionConfig();
    }

    /**
     * Create an instance of {@link DataSetCollectionConfig }
     * 
     */
    public DataSetCollectionConfig createDataSetCollectionConfig() {
        return new DataSetCollectionConfig();
    }

    /**
     * Create an instance of {@link QuerySpecConfig }
     * 
     */
    public QuerySpecConfig createQuerySpecConfig() {
        return new QuerySpecConfig();
    }

    /**
     * Create an instance of {@link CalculatorConfig }
     * 
     */
    public CalculatorConfig createCalculatorConfig() {
        return new CalculatorConfig();
    }

    /**
     * Create an instance of {@link DataSetConfig }
     * 
     */
    public DataSetConfig createDataSetConfig() {
        return new DataSetConfig();
    }

    /**
     * Create an instance of {@link ConditionsConfig }
     * 
     */
    public ConditionsConfig createConditionsConfig() {
        return new ConditionsConfig();
    }

    /**
     * Create an instance of {@link PathConfig }
     * 
     */
    public PathConfig createPathConfig() {
        return new PathConfig();
    }

    /**
     * Create an instance of {@link EntityConfig }
     * 
     */
    public EntityConfig createEntityConfig() {
        return new EntityConfig();
    }

    /**
     * Create an instance of {@link FieldConfig }
     * 
     */
    public FieldConfig createFieldConfig() {
        return new FieldConfig();
    }

}
