package nl.naturalis.nba.dao.util;

import java.io.IOException;
import java.io.InputStream;
import java.util.HashSet;
import java.util.LinkedHashSet;
import java.util.Set;

import org.apache.logging.log4j.Logger;
import org.elasticsearch.action.admin.indices.create.CreateIndexRequestBuilder;
import org.elasticsearch.action.admin.indices.create.CreateIndexResponse;
import org.elasticsearch.action.admin.indices.delete.DeleteIndexRequestBuilder;
import org.elasticsearch.action.admin.indices.delete.DeleteIndexResponse;
import org.elasticsearch.action.admin.indices.mapping.put.PutMappingRequestBuilder;
import org.elasticsearch.action.admin.indices.mapping.put.PutMappingResponse;
import org.elasticsearch.action.admin.indices.refresh.RefreshRequestBuilder;
import org.elasticsearch.action.admin.indices.settings.get.GetSettingsRequest;
import org.elasticsearch.action.admin.indices.settings.get.GetSettingsResponse;
import org.elasticsearch.action.admin.indices.settings.put.UpdateSettingsRequest;
import org.elasticsearch.action.admin.indices.settings.put.UpdateSettingsResponse;
import org.elasticsearch.action.get.GetRequestBuilder;
import org.elasticsearch.action.get.GetResponse;
import org.elasticsearch.client.Client;
import org.elasticsearch.client.IndicesAdminClient;
import org.elasticsearch.common.settings.Settings;
import org.elasticsearch.common.settings.Settings.Builder;
import org.elasticsearch.index.IndexNotFoundException;

import com.fasterxml.jackson.databind.ObjectMapper;

import nl.naturalis.nba.api.model.IDocumentObject;
import nl.naturalis.nba.api.model.SourceSystem;
import nl.naturalis.nba.common.es.map.MappingSerializer;
import nl.naturalis.nba.dao.DaoRegistry;
import nl.naturalis.nba.dao.DocumentType;
import nl.naturalis.nba.dao.ESClientManager;
import nl.naturalis.nba.dao.IndexInfo;
import nl.naturalis.nba.dao.exception.DaoException;

/**
 * Methods for interacting with Elasticsearch, mostly intended to be used for
 * unit testing and by the data import programs in {@code nl.naturalis.nba.etl}.
 * 
 * @author Ayco Holleman
 *
 */
public class ESUtil {

	private static final Logger logger = DaoRegistry.getInstance().getLogger(ESUtil.class);

	private ESUtil()
	{
	}

	/**
	 * Generates the value of the Elasticsearch _id field based on the source
	 * system of the record and the id the record had in the source system.
	 * Values for the _id field are never auto-generated by Elasticsearch.
	 * Instead, the value is generated as follows:
	 * {@code sourceSystemId + '@' + sourceSystem.getCode()}.
	 * 
	 * @param sourceSystem
	 * @param sourceSystemId
	 * @return
	 */
	public static String getElasticsearchId(SourceSystem sourceSystem, String sourceSystemId)
	{
		return sourceSystemId + '@' + sourceSystem.getCode();
	}

	/**
	 * Generates the value of the Elasticsearch _id field based on the source
	 * system of the record and the id the record had in the source system.
	 * 
	 * @param sourceSystem
	 * @param sourceSystemId
	 * @return
	 */
	public static String getElasticsearchId(SourceSystem sourceSystem, int sourceSystemId)
	{
		return sourceSystemId + '@' + sourceSystem.getCode();
	}

	/**
	 * Returns all indices hosting the NBA {@link DocumentType document types}.
	 * Document types may share an index, but this method only returns unique
	 * indices.
	 * 
	 * @return
	 */
	public static Set<IndexInfo> getDistinctIndices()
	{
		Set<IndexInfo> result = new HashSet<>(3);
		result.add(DocumentType.SPECIMEN.getIndexInfo());
		result.add(DocumentType.TAXON.getIndexInfo());
		result.add(DocumentType.MULTI_MEDIA_OBJECT.getIndexInfo());
		result.add(DocumentType.GEO_AREA.getIndexInfo());
		return result;
	}

	/**
	 * Returns the unique indices for the specified document types.
	 * 
	 * @param documentTypes
	 * @return
	 */
	public static Set<IndexInfo> getDistinctIndices(DocumentType<?>... documentTypes)
	{
		LinkedHashSet<IndexInfo> result = new LinkedHashSet<>(3);
		for (DocumentType<?> dt : documentTypes) {
			result.add(dt.getIndexInfo());
		}
		return result;
	}

	/**
	 * Deletes all indices used by the NBA. All NBA data will be lost. WATCH
	 * OUT!
	 */
	public static void deleteAllIndices()
	{
		for (IndexInfo index : getDistinctIndices()) {
			deleteIndex(index);
		}
	}

	/**
	 * Creates the Elasticsearch indices for the NBA {@link DocumentType
	 * document types}.
	 */
	public static void createAllIndices()
	{
		for (IndexInfo index : getDistinctIndices()) {
			createIndex(index);
		}
	}

	/**
	 * Deletes the Elasticsearch index hosting the specified {@link DocumentType
	 * document type}.
	 * 
	 * @param documentType
	 */
	public static void deleteIndex(DocumentType<?> documentType)
	{
		deleteIndex(documentType.getIndexInfo());
	}

	/**
	 * Deletes the specified Elasticsearch index.
	 * 
	 * @param indexInfo
	 */
	public static void deleteIndex(IndexInfo indexInfo)
	{
		String index = indexInfo.getName();
		logger.info("Deleting index {}", index);
		DeleteIndexRequestBuilder request = indices().prepareDelete(index);
		try {
			DeleteIndexResponse response = request.execute().actionGet();
			if (!response.isAcknowledged()) {
				throw new RuntimeException("Failed to delete index " + index);
			}
			logger.info("Index deleted");
		}
		catch (IndexNotFoundException e) {
			logger.info("No such index \"{}\" (nothing deleted)", index);
		}
	}

	/**
	 * Creates an Elasticsearch index for the specified {@link DocumentType
	 * document type}.
	 * 
	 * @param documentType
	 */
	public static void createIndex(DocumentType<?> documentType)
	{
		createIndex(documentType.getIndexInfo());
	}

	/**
	 * Creates the specified index.
	 * 
	 * @param indexInfo
	 */
	public static void createIndex(IndexInfo indexInfo)
	{
		String index = indexInfo.getName();
		logger.info("Creating index {}", index);
		// First load non-user-configurable settings
		String resource = "/es-settings.json";
		InputStream is = ESUtil.class.getResourceAsStream(resource);
		Builder builder = Settings.settingsBuilder();
		builder.loadFromStream(resource, is);
		// Then add user-configurable settings
		builder.put("index.number_of_shards", indexInfo.getNumShards());
		builder.put("index.number_of_replicas", indexInfo.getNumReplicas());
		CreateIndexRequestBuilder request = indices().prepareCreate(index);
		request.setSettings(builder.build());
		CreateIndexResponse response = request.execute().actionGet();
		if (!response.isAcknowledged()) {
			throw new DaoException("Failed to create index " + index);
		}
		logger.info("Created index {}", index);
		for (DocumentType<?> dt : indexInfo.getTypes()) {
			createType(dt);
		}
	}

	/**
	 * Refreshes the index hosting the specified {@link DocumentType document
	 * type} (forcing all imported data to become "visible").
	 * 
	 * @param documentType
	 */
	public static void refreshIndex(DocumentType<?> documentType)
	{
		refreshIndex(documentType.getIndexInfo());
	}

	/**
	 * Refreshed the specified index (forcing all imported data to become
	 * "visible").
	 * 
	 * @param indexInfo
	 */
	public static void refreshIndex(IndexInfo indexInfo)
	{
		String index = indexInfo.getName();
		RefreshRequestBuilder request = indices().prepareRefresh(index);
		request.execute().actionGet();
	}

	/**
	 * Returns the index refresh interval for the specified index.
	 * 
	 * @param indexInfo
	 * @return
	 */
	public static String getAutoRefreshInterval(IndexInfo indexInfo)
	{
		String index = indexInfo.getName();
		GetSettingsRequest request = new GetSettingsRequest();
		GetSettingsResponse response = indices().getSettings(request).actionGet();
		try {
			return response.getSetting(index, "index.refresh_interval");
		}
		/*
		 * Hack to work around a bug in Elasticsearch (2.3.3). You get a nasty
		 * NullPointerException if the index does not exist, or if no settings
		 * have been explicitly set for it.
		 */
		catch (NullPointerException e) {
			return null;
		}
	}

	/**
	 * Sets the index refresh interval for -1 for the specified index.
	 * 
	 * @param indexInfo
	 * @return The original refresh interval
	 */
	public static String disableAutoRefresh(IndexInfo indexInfo)
	{
		String index = indexInfo.getName();
		logger.info("Disabling auto-refresh for index " + index);
		String origValue = getAutoRefreshInterval(indexInfo);
		UpdateSettingsRequest request = new UpdateSettingsRequest(index);
		Builder builder = Settings.settingsBuilder();
		builder.put("index.refresh_interval", -1);
		request.settings(builder.build());
		UpdateSettingsResponse response = indices().updateSettings(request).actionGet();
		if (!response.isAcknowledged()) {
			String msg = "Failed to disable auto-refresh for index " + index;
			throw new DaoException(msg);
		}
		return origValue;
	}

	/**
	 * Sets the index refresh interval for the specified index.
	 * 
	 * @param indexInfo
	 * @param interval
	 */
	public static void setAutoRefreshInterval(IndexInfo indexInfo, String interval)
	{
		if (interval == null) {
			logger.warn("Setting the index refresh interval to null has no effect");
			return;
		}
		String index = indexInfo.getName();
		logger.info("Updating index refresh interval for index " + index);
		UpdateSettingsRequest request = new UpdateSettingsRequest(index);
		Builder builder = Settings.settingsBuilder();
		builder.put("index.refresh_interval", interval);
		request.settings(builder.build());
		UpdateSettingsResponse response = indices().updateSettings(request).actionGet();
		if (!response.isAcknowledged()) {
			String msg = "Failed to update index refresh interval for index " + index;
			throw new DaoException(msg);
		}
	}

	/**
	 * Creates a type mapping for the specified {@link DocumentType document
	 * type}.
	 * 
	 * @param dt
	 */
	public static <T extends IDocumentObject> void createType(DocumentType<T> dt)
	{
		String index = dt.getIndexInfo().getName();
		String type = dt.getName();
		logger.info("Creating type {} in index {}", type, index);
		PutMappingRequestBuilder request = indices().preparePutMapping(index);
		MappingSerializer<T> serializer = new MappingSerializer<>();
		String source = serializer.serialize(dt.getMapping());
		request.setSource(source);
		request.setType(type);
		try {
			PutMappingResponse response = request.execute().actionGet();
			if (!response.isAcknowledged()) {
				throw new DaoException("Failed to create type " + type);
			}
			logger.info("Created type {}", type);
		}
		catch (Throwable t) {
			String fmt = "Failed to create type %s: %s";
			String msg = String.format(fmt, type, t.getMessage());
			if (logger.isDebugEnabled()) {
				logger.debug(t);
			}
			throw new DaoException(msg);
		}
	}

	/**
	 * Retrieves the document with the specified {@code _id} and converts it to
	 * an instance of the class corresponding to the specified
	 * {@link DocumentType document type}.
	 * 
	 * @param dt
	 * @param id
	 * @return
	 */
	public static <T extends IDocumentObject> T find(DocumentType<T> dt, String id)
	{
		String index = dt.getIndexInfo().getName();
		String type = dt.getName();
		Class<T> cls = dt.getJavaType();
		ObjectMapper objectMapper = dt.getObjectMapper();
		Client client = ESClientManager.getInstance().getClient();
		GetRequestBuilder grb = client.prepareGet(index, type, id);
		GetResponse response = grb.execute().actionGet();
		if (response.isExists()) {
			try {
				return objectMapper.readValue(response.getSourceAsBytes(), cls);
			}
			catch (IOException e) {
				throw new DaoException(e);
			}
		}
		return null;
	}

	private static IndicesAdminClient indices()
	{
		return ESClientManager.getInstance().getClient().admin().indices();
	}

}
