//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.11.18 at 02:53:08 PM CET 
//


package org.tdwg.schemas.abcd._2;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.NormalizedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * Details of the country
 * 
 * <p>Java class for Country complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Country">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Name" type="{http://www.tdwg.org/schemas/abcd/2.06}StringL" minOccurs="0"/>
 *         &lt;element name="NameDerived" type="{http://www.tdwg.org/schemas/abcd/2.06}StringL" minOccurs="0"/>
 *         &lt;element name="ISO3166Code" type="{http://www.tdwg.org/schemas/abcd/2.06}String" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Country", propOrder = {
    "name",
    "nameDerived",
    "iso3166Code"
})
public class Country {

    @XmlElement(name = "Name")
    protected StringL name;
    @XmlElement(name = "NameDerived")
    protected StringL nameDerived;
    @XmlElement(name = "ISO3166Code")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String iso3166Code;

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link StringL }
     *     
     */
    public StringL getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link StringL }
     *     
     */
    public void setName(StringL value) {
        this.name = value;
    }

    /**
     * Gets the value of the nameDerived property.
     * 
     * @return
     *     possible object is
     *     {@link StringL }
     *     
     */
    public StringL getNameDerived() {
        return nameDerived;
    }

    /**
     * Sets the value of the nameDerived property.
     * 
     * @param value
     *     allowed object is
     *     {@link StringL }
     *     
     */
    public void setNameDerived(StringL value) {
        this.nameDerived = value;
    }

    /**
     * Gets the value of the iso3166Code property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getISO3166Code() {
        return iso3166Code;
    }

    /**
     * Sets the value of the iso3166Code property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setISO3166Code(String value) {
        this.iso3166Code = value;
    }

}
