#!/bin/bash

. ./include.sh

action="${1}"

if [ "$action" = fast ]
then
    java -cp ${classpath} ${JAVA_OPTS} ${root_package}.brahms.BrahmsDuplicateChecker
elif [ "$action" = file ]
then
    java -cp ${classpath} ${JAVA_OPTS} ${root_package}.brahms.BrahmsDuplicateChecker ${action}
elif [ "$action" = all ]
then
    java -cp ${classpath} ${JAVA_OPTS} ${root_package}.brahms.BrahmsDuplicateChecker ${action}  
elif [ "x$action" = x ]
then
    java -cp ${classpath} ${JAVA_OPTS} ${root_package}.brahms.BrahmsDuplicateChecker
else
    echo "Unknown option: \"$action\". Please use \"fast\", \"file\", or \"all\" (or leave blank for fast check)."
fi