#!/bin/bash

. ./include.sh

action="${1}"

if [ "$action" = detailed ]
then
    java -cp ${classpath} ${JAVA_OPTS} ${root_package}.brahms.BrahmsDuplicateChecker ${action}
    
elif [ "x$action" = x ]
then
    java -cp ${classpath} ${JAVA_OPTS} ${root_package}.brahms.BrahmsDuplicateChecker
else
    echo "Don't know how to import/execute \"$action\"."
fi