#!/bin/bash

. ./include.sh

type="${1}"

if [ "x${type}" = x ]
then
	java -cp ${classpath} $JAVA_OPTS ${root_package}.crs.CrsImportAll
elif [ "${type}" = specimens ]
then
	java -cp ${classpath} $JAVA_OPTS ${root_package}.crs.CrsSpecimenImportOffline
elif [ "${type}" = multimedia ]
then
	java -cp ${classpath} $JAVA_OPTS ${root_package}.crs.CrsMultiMediaImportOffline
else
	echo "USAGE: ${0} [ specimens | multimedia ]"
fi



