#!/bin/bash

. ./include.sh

# The number of multimedia documents read and process at once
read_batch_size=500
# The number of enriched multimedia documents to re-index at once
write_batch_size=500
# The read timeout in milliseconds
scroll_timeout=60000

action="${1}"

if [ "${action}" = nullify ]
then
	java -cp ${classpath} $JAVA_OPTS ${root_package}.enrich.MultiMediaObjectEnrichmentNullifier
else
	JAVA_OPTS="$JAVA_OPTS -Dnl.naturalis.nba.etl.enrich.readBatchSize=${read_batch_size}"
	JAVA_OPTS="$JAVA_OPTS -Dnl.naturalis.nba.etl.enrich.writeBatchSize=${write_batch_size}"
	JAVA_OPTS="$JAVA_OPTS -Dnl.naturalis.nba.etl.enrich.scrollTimeout=${scroll_timeout}"
	java -cp ${classpath} $JAVA_OPTS ${root_package}.enrich.MultiMediaObjectEnricher
fi
