#!/bin/bash

action="${1}"

if [ "${action}" = noscript ]
then
	java -cp ${classpath} $JAVA_OPTS ${root_package}.NbaImportAll
	exit 0
fi

start=$(date)

scripts=" \
	bootstrap_all \
	nsr-import_reset \
	nsr-import_taxa \
	nsr-import_multimedia \
	geo-import \
	col-import \
	brahms-import_reset \
	brahms-import_specimens \
	brahms-import_multimedia \
	crs-import_specimens \
	crs-import_multimedia \
	enrich-specimens
	name-import \
	"

for script in $scripts
do
  script=${script/_/ }
  echo
  echo Executing $script ...
  script="./${script}"
  $script
  result=$?
  if [ "$result" != 0 ]
  then
    finish=$(date)
    echo "Error while executing $script. Import aborted"
	echo "Import started at ${start}"
	echo "Import aborted at ${finish}"
    exit $result
  fi
done

finish=$(date)

echo "Import started at ${start}"
echo "Import finished at ${finish}"


