#!/bin/bash

. ./include.sh

type="${1}"

if [ "${type}" = specimen ]
then
    java -cp ${classpath} $JAVA_OPTS ${root_package}.JsonImporter Specimen
elif [ "${type}" = multimedia ]
then
    java -cp ${classpath} $JAVA_OPTS ${root_package}.JsonImporter MultiMediaObject
elif [ "${type}" = all ]
then
    java -cp ${classpath} $JAVA_OPTS ${root_package}.JsonImporter Specimen
    java -cp ${classpath} $JAVA_OPTS ${root_package}.JsonImporter MultiMediaObject
else
    echo "USAGE: ${0} [ specimen | multimedia | all ]"
fi