#!/bin/bash

# USAGE: truncate <document_type> [<source_system>]
# Deletes all document of the specified type and source system.
# For help, just type truncate.

. ./include.sh

java -cp ${classpath} $JAVA_OPTS ${root_package}.NbaTruncate $@

