package nl.naturalis.nba.dao.es;

import static nl.naturalis.nba.api.query.Operator.EQUALS;
import static nl.naturalis.nba.api.query.Operator.LIKE;
import static nl.naturalis.nba.dao.es.ESTestUtils.createIndex;
import static nl.naturalis.nba.dao.es.ESTestUtils.createType;
import static nl.naturalis.nba.dao.es.ESTestUtils.dropIndex;
import static nl.naturalis.nba.dao.es.ESTestUtils.refreshIndex;
import static nl.naturalis.nba.dao.es.ESTestUtils.saveObject;
import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertNotNull;

import org.junit.After;
import org.junit.Before;
import org.junit.BeforeClass;
import org.junit.Test;

import nl.naturalis.nba.api.model.Agent;
import nl.naturalis.nba.api.model.Person;
import nl.naturalis.nba.api.model.Specimen;
import nl.naturalis.nba.api.query.Condition;
import nl.naturalis.nba.api.query.InvalidQueryException;
import nl.naturalis.nba.api.query.QuerySpec;
import nl.naturalis.nba.dao.es.transfer.SpecimenTransfer;
import nl.naturalis.nba.dao.es.types.ESSpecimen;

public class SpecimenDAOTest {

	static ESSpecimen pMajor;
	static ESSpecimen lFuscus;
	static ESSpecimen tRex;
	static ESSpecimen mSylvestris;

	@BeforeClass
	public static void setup()
	{
		pMajor = TestSpecimens.parusMajorSpecimen01();
		lFuscus = TestSpecimens.tRexSpecimen01();
	}

	@Before
	public void before()
	{
		dropIndex(ESSpecimen.class);
		createIndex(ESSpecimen.class);
		createType(ESSpecimen.class);
		pMajor = TestSpecimens.parusMajorSpecimen01();
		lFuscus = TestSpecimens.larusFuscusSpecimen01();
		tRex = TestSpecimens.tRexSpecimen01();
		mSylvestris = TestSpecimens.malusSylvestrisSpecimen01();
		ESTestUtils.saveSpecimens(pMajor, lFuscus, tRex, mSylvestris);
	}

	@After
	public void after()
	{
		//dropIndex(ESSpecimen.class);
	}

	/*
	 * Test lookup using internal Elasticsearch ID.
	 */
	@Test
	public void testFindById_1()
	{
		/*
		 * Internal Elasticsearch system IDs are generated by concatening UnitID
		 * and source system code, like so:
		 */
		String id = pMajor.getUnitID() + "@" + pMajor.getSourceSystem().getCode();
		SpecimenDAO dao = new SpecimenDAO();
		Specimen out = dao.find(id);
		assertNotNull("01", out);
	}

	/*
	 * Test lookup of Parus major specimen using UnitID.
	 */
	@Test
	public void testFindByUnitID_1()
	{
		String unitID = pMajor.getUnitID();
		SpecimenDAO dao = new SpecimenDAO();
		Specimen[] result = dao.findByUnitID(unitID);
		assertNotNull("01", result);
		assertEquals("02", 1, result.length);
		/*
		 * Make sure no weird analysis stuff is going on
		 */
		result = dao.findByUnitID("ZMA");
		assertNotNull("05", result);
		assertEquals("06", 0, result.length);
		result = dao.findByUnitID("100");
		assertNotNull("07", result);
		assertEquals("08", 0, result.length);
	}

	/*
	 * Test lookup of Larus fuscus specimen using UnitID.
	 */
	@Test
	public void testFindByUnitID_2()
	{
		String unitID0 = lFuscus.getUnitID();
		SpecimenDAO dao = new SpecimenDAO();
		Specimen[] result = dao.findByUnitID(unitID0);
		assertNotNull("01", result);
		assertEquals("02", 1, result.length);
		assertEquals("03", unitID0, result[0].getUnitID());
		/*
		 * Make sure no weird analysis stuff is going on
		 */
		result = dao.findByUnitID("L");
		assertNotNull("04", result);
		assertEquals("05", 0, result.length);
	}

	/*
	 * Test lookup using non-existent UnitID.
	 */
	@Test
	public void testFindByUnitID_3()
	{
		SpecimenDAO dao = new SpecimenDAO();
		Specimen[] result = dao.findByUnitID("BLA DI BLA");
		assertNotNull("01", result);
		assertEquals("02", 0, result.length);
	}

	/*
	 * Tests findByCollector using Parus major specimen.
	 */
	@Test
	public void testFindByCollector_1()
	{
		SpecimenDAO dao = new SpecimenDAO();
		Person person = pMajor.getGatheringEvent().getGatheringPersons().get(0);
		String collector = person.getFullName();
		Specimen[] result = dao.findByCollector(collector);
		assertNotNull("01", result);
		assertNotNull("02", result[0]);
		assertNotNull("03", result[0].getGatheringEvent());
		assertNotNull("04", result[0].getGatheringEvent().getGatheringPersons());
		Agent agent = result[0].getGatheringEvent().getGatheringPersons().get(0);
		assertNotNull("05", agent);
		assertEquals("06", Person.class, agent.getClass());
		Person personOut = (Person) agent;
		assertEquals("07", person, personOut);
	}

	/*
	 * Tests query method with a single EQUALS query condition.
	 */
	@Test
	public void testQuery__QuerySpec__01() throws InvalidQueryException
	{
		String unitID = pMajor.getUnitID();
		Condition condition = new Condition("unitID", EQUALS, unitID);
		QuerySpec qs = new QuerySpec();
		qs.setCondition(condition);
		SpecimenDAO dao = new SpecimenDAO();
		Specimen[] result = dao.query(qs);
		assertEquals("01", 1, result.length);
		assertEquals("02", pMajor.getUnitID(), result[0].getUnitID());
	}

	/*
	 * Tests query method with two EQUALS query conditions combined using AND.
	 */
	@Test
	public void testQuery__QuerySpec__02() throws InvalidQueryException
	{
		String genus = "identifications.defaultClassification.genus";
		String species = "identifications.defaultClassification.specificEpithet";
		Condition condition = new Condition(genus, "=", "Parus");
		condition.and(species, EQUALS, "major");
		QuerySpec qs = new QuerySpec();
		qs.setCondition(condition);
		SpecimenDAO dao = new SpecimenDAO();
		Specimen[] result = dao.query(qs);
		assertEquals("01", 1, result.length);
	}

	/*
	 * Tests query method with using two ANDed conditions, one known to be
	 * false.
	 */
	@Test
	public void testQuery__QuerySpec__03() throws InvalidQueryException
	{
		String genus = "identifications.defaultClassification.genus";
		String species = "identifications.defaultClassification.specificEpithet";
		Condition condition = new Condition(genus, EQUALS, "Parus");
		condition.and(species, EQUALS, "BLA DI BLA");
		QuerySpec qs = new QuerySpec();
		qs.setCondition(condition);
		SpecimenDAO dao = new SpecimenDAO();
		Specimen[] result = dao.query(qs);
		assertEquals("01", 0, result.length);
	}

	/*
	 * Tests query method with two EQUALS query conditions combined using OR.
	 */
	@Test
	public void testQuery__QuerySpec__04() throws InvalidQueryException
	{
		String genus = "identifications.defaultClassification.genus";
		String species = "identifications.defaultClassification.specificEpithet";
		Condition condition = new Condition(genus, EQUALS, "Parus");
		condition.or(species, EQUALS, "major");
		QuerySpec qs = new QuerySpec();
		qs.setCondition(condition);
		SpecimenDAO dao = new SpecimenDAO();
		Specimen[] result = dao.query(qs);
		assertEquals("01", 1, result.length);
	}

	/*
	 * Tests query method with using two ORed conditions, one known to be false.
	 */
	@Test
	public void testQuery__QuerySpec__05() throws InvalidQueryException
	{
		String genus = "identifications.defaultClassification.genus";
		String species = "identifications.defaultClassification.specificEpithet";
		Condition condition = new Condition(genus, EQUALS, "Parus");
		condition.or(species, EQUALS, "BLA DI BLA");
		QuerySpec qs = new QuerySpec();
		qs.setCondition(condition);
		SpecimenDAO dao = new SpecimenDAO();
		Specimen[] result = dao.query(qs);
		assertEquals("01", 1, result.length);
	}

	/*
	 * Tests query method with using two ORed conditions, both known to be
	 * false.
	 */
	@Test
	public void testQuery__QuerySpec__06() throws InvalidQueryException
	{
		String genus = "identifications.defaultClassification.genus";
		String species = "identifications.defaultClassification.specificEpithet";
		Condition condition = new Condition(genus, EQUALS, "BLA DI BLA");
		condition.or(species, EQUALS, "BLA DI BLA");
		QuerySpec qs = new QuerySpec();
		qs.setCondition(condition);
		SpecimenDAO dao = new SpecimenDAO();
		Specimen[] result = dao.query(qs);
		assertEquals("01", 0, result.length);
	}

	/*
	 * Test query method with LIKE operator.
	 */
	@Test
	public void testQuery__QuerySpec__07() throws InvalidQueryException
	{
		String collector = "gatheringEvent.gatheringPersons.fullName";
		Condition condition = new Condition(collector, LIKE, "altenburg");
		QuerySpec qs = new QuerySpec();
		qs.setCondition(condition);
		SpecimenDAO dao = new SpecimenDAO();
		Specimen[] result = dao.query(qs);
		assertEquals("01", 1, result.length);
	}

	/*
	 * Test save method
	 */
	@Test
	public void testSave__Specimen__01()
	{
		Specimen toBeSaved = SpecimenTransfer.load(pMajor, null);
		SpecimenDAO dao = new SpecimenDAO();
		String id = dao.save(toBeSaved, true);
		assertNotNull("01", id);
		Specimen retrieved = dao.find(id);
		assertNotNull("02", retrieved);
		assertEquals("03", pMajor.getUnitID(), retrieved.getUnitID());
	}

}
